feat(buttons): created a renderdiv to render a person in a div
solid/solid-ui pull request #415
Opened 2021-06-21 09:50 UTC by SharonStrats

**Overview**
This PR adds a new function renderAsDiv which will render a person (image, name, and link) in a div.
1) includes renderAsDiv function
2) a bit of a refactor.
3) Tests
4) And a storybook example

No breaking changes.

2021-06-21 17:39 UTC, TallTed requested changes

2021-06-21 17:39 UTC, TallTed commented on src/stories/Interactive.stories.mdx
> +A Div to represent a draggable person, etc in a list
```suggestion
A Div to represent (a) draggable person(s), etc., in a list
```

2021-06-21 17:39 UTC, TallTed commented on test/unit/widgets/buttons/iconLink.test.ts
> +  it('creates a Link for a URI element should return with two children a tag and br tag', () => {
```suggestion
  it('creates a Link for a URI element; should return with two children: a tag and br tag', () => {
```

2021-06-25 15:51 UTC, angelo-v requested changes

2021-06-25 15:51 UTC, angelo-v commented on src/stories/Interactive.stories.mdx
> +<Canvas>
**praise** Thanks for adding a story.

**issue** It does not look well aligend, is this only in storybook or a general problem with the component?

![](https://user-images.githubusercontent.com/340725/123448937-7e647900-d5db-11eb-84a7-289cfc269921.png)

2021-06-25 15:51 UTC, angelo-v commented on src/stories/Interactive.stories.mdx
> +[API documentation](https://solid.github.io/solid-ui/Documentation/api/modules/_widgets_buttons_.html#persontr)
**issue** The documentation link is wrong, it should not point to persontr. Besides that all those links seem to be broken, perhaps you can update them

2021-06-25 15:51 UTC, angelo-v commented on test/unit/widgets/buttons.test.ts
> +  it.skip('adds the deleteFunction of .... deleteButton with Check', () => {
**issue** this test should not be skipped
You are probably missing `deleteButton.setAttribute('role', 'button')` to make this test work

2021-06-25 19:59 UTC, merged

2021-06-25 20:18 UTC, bourgeoa commented
Sorry @angelo-v I did not see all comments and requested changes.
Having never tested reverting a PR I prefer to keep it.

@SharonStrats you can add your changes after merging