Fix typos; closes #429
solid/solid-ui pull request #432
Opened 2021-09-27 15:35 UTC by janschill

Regarding the talked about typos in https://github.com/solid/solid-ui/issues/429

2021-09-27 18:59 UTC, TallTed approved these changes
LGTM!

2021-09-27 19:54 UTC, bourgeoa commented
Fail on lint

2021-09-27 20:25 UTC, TallTed commented on src/widgets/forms/autocomplete/language.ts
> +export function addDefaults(array) {
```suggestion
export function addDefaults (array) {
```

2021-09-27 20:25 UTC, TallTed commented on src/widgets/forms/autocomplete/language.ts
> +export async function getPreferredLanguagesFor(person: NamedNode) {
```suggestion
export async function getPreferredLanguagesFor (person: NamedNode) {
```

2021-09-27 20:25 UTC, TallTed commented on src/widgets/forms/autocomplete/language.ts
> +export async function getPreferredLanguages() {
```suggestion
export async function getPreferredLanguages () {
```

2021-09-27 20:26 UTC, TallTed commented on src/widgets/forms/autocomplete/language.ts
> +export function filterByLanguage(bindings, languagePrefs) {
```suggestion
export function filterByLanguage (bindings, languagePrefs) {
```

2021-09-27 20:27 UTC, TallTed requested changes
I don't know why these spaces were deleted in the first place ... but putting them back appears to be the path through the Lint error.

2021-09-29 09:01 UTC, janschill commented
Should be good now, sorry about that. Is there a reason you have this enabled:

>First-time contributors need a maintainer to approve running workflows.

2021-09-29 19:48 UTC, merged